- id: conftest
  name: Conftest Policy Check
  description: Validate configuration files against Open Policy Agent policies using Conftest
  entry: conftest test
  language: golang
  pass_filenames: true
  require_serial: true
  minimum_pre_commit_version: "2.9.0"
  stages: [pre-commit, pre-merge-commit, pre-push, manual]